---
- name: This is my main playbook
  hosts: all
  become: yes
  roles:
    - apache
    - php
    - composer

  tasks:
    - name: Clone the laravel repository
      git:
        repo: https://github.com/f1amy/laravel-realworld-example-app.git
        dest: /var/www/html/laravel-realworld-example-app
        clone: yes
        update: yes

    - name: Move into the Laravel Repository
      shell: cd /var/www/html/laravel-realworld-example-app

    - name: Install Laravel
      community.general.composer:
        command: create-project
        working_dir: /var/www/html/laravel-realworld-example-app
      environment:
        COMPOSER_ALLOW_SUPERUSER: 1

    - name: Change file ownership, group and permissions
      file:
        path: /var/www/html/laravel-realworld-example-app
        owner: www-data
        group: www-data
        mode: '0775'
        recurse: yes

    - name: Set up Apache virtualhost
      template:
        src: files/laravel.conf.j2
        dest: /etc/apache2/sites-available/laravel.conf
      notify: Restart Apache

    - name: Enable new site
      shell: /usr/sbin/a2ensite laravel.conf
      notify: Restart Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      notify: Restart Apache
#    - name: configure the .env file
      

# Enter command to copy bash script here
# PostgreSQL Bash script execution

# UFW Configuration

# Configure domain name biiiiitch
  handlers:
    - name: Enable Apache
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
      become: yes

    - name: Start Apache
      ansible.builtin.systemd:
        name: apache2
        state: started
      become: yes

    - name: Restart Apache
      ansible.builtin.systemd:
        name: apache2
        state: restarted
      become: yes
